In [1]:
import numpy as np

In [11]:
np.array([])

array([], dtype=float64)

In [12]:
print(type(np.array([])))

<class 'numpy.ndarray'>


In [13]:
n= np.array([1,3,4])

In [14]:
print(n)

[1 3 4]


In [15]:
b=n*2
print(b)

[2 6 8]


In [16]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
print(x[0:2,0:2])
print(x.dtype)

[[1 2]
 [4 5]]
int32


In [18]:
y=np.array([
    [[1,2],
    [3,4],
    [5,6]],
    
    [[1,2],
    [3,4],
    [5,6]],
    
    [[1,2],
    [3,4],
    [5,6]]
    
])
for i in y:
    for j in i:
        for k in j:
            print(k)
    
print(y.shape)


1
2
3
4
5
6
1
2
3
4
5
6
1
2
3
4
5
6
(3, 3, 2)


In [19]:
for i in np.nditer(y):
    print(i)

1
2
3
4
5
6
1
2
3
4
5
6
1
2
3
4
5
6
