In [8]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

b = np.array_split(a, 3)

print(b)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [22]:
x=np.array([
    [1,2],
    [3,4]
])

y = np.array_split(x, 1)
print(y)

[array([[1, 2],
       [3, 4]])]


In [30]:
p=np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

q = np.array_split(p, 2)
print(q)

[array([[[1, 2],
        [3, 4]]]), array([[[5, 6],
        [7, 8]]])]


In [31]:
p

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [32]:
p.shape

(2, 2, 2)

In [33]:
q[0]

array([[[1, 2],
        [3, 4]]])

In [34]:
q[1]

array([[[5, 6],
        [7, 8]]])

In [35]:
q[0].shape

(1, 2, 2)